version: 2

defaults: &defaults
  docker:
    - image: circleci/python:3.6.6
  working_directory: ~/flask-jwt-consumer

tags_only: &tags_only
  tags:
    only: /[0-9]+(\.[0-9]+)*/
  branches:
    ignore: /.*/

jobs:
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: Install test dependencies
          command: pipenv install --dev
      - save_cache:
          paths:
            - ./venv
          key: deps1-{{ .Branch }}-{{ checksum "Pipfile.lock" }}
      - run:
          name: Run tests
          command: pipenv run pytest tests --verbose
      - persist_to_workspace:
          root: ~/flask-jwt-consumer
          paths:
            - ./

  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/flask-jwt-consumer
      - run:
          name: Verify git tag vs. version
          command: |
            python setup.py verify
      - run:
          name: Create packages
          command: |
            python setup.py sdist
            python setup.py bdist_wheel

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/flask-jwt-consumer/dist
      - run:
          name: Init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc

      - run:
          name: Install twine
          command: pip install twine --user
      - run:
          name: Upload to pypi
          command: .local/bin/twine upload *

workflows:
  version: 2
  verify_build_and_deploy:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            <<: *tags_only
      - deploy:
          requires:
            - build
          filters:
            <<: *tags_only
