version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "Pipfile" }}
      - run:
          name: 'Install test dependencies'
          command: pipenv install
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "Pipfile" }}
      - run:
          name: 'Run tests'
          command: |
            pipenv shell
            pytest tests --verbose

workflows:
  version: 2
  main:
    jobs:
      - test