version: 2.1

orbs:
  common: syapse/common@1.4.0

workflows:
  main:
    jobs:
      - common/pybuild:
          filters:
            tags:
              only: /.*/
      - common/release:
          context: PACKAGECLOUD
          requires:
            - common/pybuild
          filters:
            tags:
              only: /.*/
      - common/release-notes:
          context: aws-ecr-prod
          requires:
            - common/release
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
