version: 2
jobs:
  test:
    docker:
      - image: circleci/python:3.6.4
    working_directory: ~/flask-jwt-consumer
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "Pipfile" }}
      - run:
          name: 'Install test dependencies'
          command: pipenv install
      - save_cache:
          paths:
            - ./venv
          key: deps1-{{ .Branch }}-{{ checksum "Pipfile" }}
      - run:
          name: 'Run tests'
          command: pipenv run pytest tests --verbose

workflows:
  version: 2
  main:
    jobs:
      - test